openapi: 3.0.3
info:
  title: ITspace - OpenAPI 3.0
  description: |-
     itSpace API documentation, binar final project K13
  contact:
    email: rian.rafli@gmail.com
  version: 1.0.0
servers:
  - url: http://localhost:8000/api/v1
tags:
  - name: courses
    description: Everything about courses
  - name: courses
    description: Access to Petstore orders
    externalDocs:
      description: Find out more about our store
      url: http://swagger.io
paths:
  /courses:
    post:
      tags:
        - courses
      description: create new course
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Courses'
      responses:
        '201':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/basicResponse'          
      

components:
  schemas:
    basicResponse:
      type: object
      properties:
        success:
          type: boolean
          example: true
        message:
          type: string
          example: "successfully do task"
        data:
          type: object

    Courses:
      type: object
      properties:
        title:
          type: string
          example: Backend dengan expressjs
        price:
          type: integer
          example: 200000
        level:
          type: string
          example: BEGINNER
        isPremium:
          type: boolean
          example: true
        description:
          type: string
          example: "course ini akan mengejarkan kamu tentang API"
        category:
          type: array
          example : ["Backend","Database"]
        mentor:
           type: array
           example : ["rian@gmail.com","rafli@gmail.com"]
